### ISSUE TITLE
Feature Request: Add an option to choose a font for the markdown.

### ISSUE THREAD

**Issue by YousufSSyed** [kometenstaub/obsidian-version-history-diff#21]

**Comment by kometenstaub** [comment]
That should already be possible with a CSS snippet:

```css
.diff .d2h-code-line-ctn {
    font-family: "My font";
}
```
